apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agora
resources:
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
images:
  - name: ghcr.io/andrescastiglia/agora
    digest: sha256:719cf8dbc49a77ef3a7f7294e386e7e7a519957b237c5b320da0984988aea288
